#!/usr/bin/env bash
# {{APP}} — build a signed, App Store Connect–ready IPA. Generated by flutter-ios-release.
# Run on macOS from anywhere:   bash ios-release/build-ios.sh [--team-id ABCDE12345] [--skip-tests]
#
# Needs: macOS, Xcode 26+ (iOS 26 SDK — App Store Connect minimum since 2026-04-28), Flutter, an
# Apple Developer Program membership, and the app record for {{BUNDLE_ID}} in App Store Connect.
# Signing is automatic (-allowProvisioningUpdates), authenticated EITHER by an Apple ID of the team
# signed in to Xcode (Settings → Accounts) OR by an App Store Connect API key in the environment:
#   ASC_KEY_ID  ASC_ISSUER_ID  ASC_KEY_PATH=/abs/path/AuthKey_XXXXXXXXXX.p8   (never commit the .p8)
# Team: --team-id > $IOS_TEAM_ID > DEVELOPMENT_TEAM in the Xcode project > teamID in ExportOptions.plist.
#
# Output: build/ios/ipa/*.ipa and ios-release/build-verify.json. This script NEVER uploads.
# Exit 0 = IPA built and verified · 1 = build or verification failed · 2 = environment/usage.
# Bash 3.2 compatible (macOS /bin/bash).
set -uo pipefail

KIT=$(cd "$(dirname "$0")" && pwd); ROOT=$(cd "$KIT/.." && pwd); cd "$ROOT" || exit 2
TEAM="${IOS_TEAM_ID:-}"; SKIP_TESTS=false
while [ $# -gt 0 ]; do
  case "$1" in
    --team-id) [ $# -ge 2 ] || { echo "--team-id needs a value" >&2; exit 2; }; TEAM="$2"; shift 2;;
    --skip-tests) SKIP_TESTS=true; shift;;
    -h|--help) sed -n '2,15p' "$0"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done
die() { echo "ERROR: $*" >&2; exit "${2:-2}"; }
step() { printf '\n== %s\n' "$*"; }
PB=/usr/libexec/PlistBuddy

step "environment"
[ "$(uname -s)" = Darwin ] || die "macOS required — this kit was prepared on another OS; run it on a Mac"
command -v xcodebuild >/dev/null || die "Xcode not installed (xcode-select --install is not enough)"
command -v flutter >/dev/null || die "flutter not on PATH"
XV=$(xcodebuild -version | awk '/^Xcode/{print $2}'); SDK=$(xcrun --sdk iphoneos --show-sdk-version 2>/dev/null)
echo "Xcode $XV · iOS SDK $SDK · $(flutter --version 2>/dev/null | head -1)"
[ "${XV%%.*}" -ge 26 ] 2>/dev/null || die "Xcode $XV < 26 — App Store Connect rejects builds made with an older SDK"

EXPORT_SRC="$KIT/ExportOptions.plist"; [ -f "$EXPORT_SRC" ] || die "missing $EXPORT_SRC"
if [ -z "$TEAM" ]; then
  TEAM=$(sed -n 's/^[[:space:]]*DEVELOPMENT_TEAM = \([A-Z0-9]\{10\}\);/\1/p' ios/Runner.xcodeproj/project.pbxproj | head -1)
fi
[ -n "$TEAM" ] || TEAM=$("$PB" -c 'Print :teamID' "$EXPORT_SRC" 2>/dev/null || true)
[[ "$TEAM" =~ ^[A-Z0-9]{10}$ ]] || die "no Apple team id — pass --team-id or IOS_TEAM_ID (developer.apple.com → Membership)"
AUTH=()
if [ -n "${ASC_KEY_ID:-}${ASC_ISSUER_ID:-}${ASC_KEY_PATH:-}" ]; then
  [ -n "${ASC_KEY_ID:-}" ] && [ -n "${ASC_ISSUER_ID:-}" ] && [ -f "${ASC_KEY_PATH:-/nonexistent}" ] \
    || die "ASC_KEY_ID, ASC_ISSUER_ID and ASC_KEY_PATH (existing .p8) must all be set"
  AUTH=(-authenticationKeyPath "$ASC_KEY_PATH" -authenticationKeyID "$ASC_KEY_ID" -authenticationKeyIssuerID "$ASC_ISSUER_ID")
  echo "auth: App Store Connect API key $ASC_KEY_ID"
else
  echo "auth: Apple ID signed in to Xcode (no ASC_* variables)"
fi
echo "team: $TEAM · bundle id: {{BUNDLE_ID}}"

step "flutter pub get / tests"
flutter pub get || die "flutter pub get failed" 1
$SKIP_TESTS || [ ! -d test ] || flutter test || die "flutter test failed — fix before shipping" 1
flutter build ios --release --config-only || die "flutter build ios --config-only failed" 1

step "archive"
ARCHIVE="$ROOT/build/ios/archive/Runner.xcarchive"; OUT="$ROOT/build/ios/ipa"
rm -rf "$ARCHIVE" "$OUT"; mkdir -p "$ROOT/build/ios"
xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release \
  -destination 'generic/platform=iOS' -archivePath "$ARCHIVE" \
  DEVELOPMENT_TEAM="$TEAM" -allowProvisioningUpdates ${AUTH[@]+"${AUTH[@]}"} archive \
  > "$ROOT/build/ios/archive.log" 2>&1 || { tail -40 "$ROOT/build/ios/archive.log"; die "archive failed — full log: build/ios/archive.log" 1; }

step "export (app-store-connect, destination=export — no upload)"
EXPORT="$ROOT/build/ios/ExportOptions.plist"; cp "$EXPORT_SRC" "$EXPORT"
"$PB" -c "Set :teamID $TEAM" "$EXPORT" 2>/dev/null || "$PB" -c "Add :teamID string $TEAM" "$EXPORT"
"$PB" -c "Set :destination export" "$EXPORT" 2>/dev/null || "$PB" -c "Add :destination string export" "$EXPORT"
xcodebuild -exportArchive -archivePath "$ARCHIVE" -exportOptionsPlist "$EXPORT" -exportPath "$OUT" \
  -allowProvisioningUpdates ${AUTH[@]+"${AUTH[@]}"} > "$ROOT/build/ios/export.log" 2>&1 \
  || { tail -40 "$ROOT/build/ios/export.log"; die "export failed — full log: build/ios/export.log" 1; }

step "verify"
IPA=$(ls "$OUT"/*.ipa 2>/dev/null | head -1); [ -n "$IPA" ] || die "no .ipa in $OUT" 1
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
unzip -q "$IPA" -d "$TMP" || die "cannot unzip $IPA" 1
APP=$(ls -d "$TMP"/Payload/*.app | head -1); PL="$APP/Info.plist"
rd() { "$PB" -c "Print :$1" "$PL" 2>/dev/null; }
PUB=$(sed -n 's/^version:[[:space:]]*\([^[:space:]]*\).*/\1/p' pubspec.yaml); PUB_NAME=${PUB%%+*}; PUB_BUILD=${PUB##*+}
FAIL=0; ROWS=""
chk() { # name ok|fail detail
  printf '%-14s %s %s\n' "$1" "$([ "$2" = ok ] && echo ✅ || echo ❌)" "$3"
  [ "$2" = ok ] || FAIL=1
  ROWS="$ROWS${ROWS:+,}{\"check\":\"$1\",\"status\":\"$2\",\"detail\":\"$(printf '%s' "$3" | sed 's/\\/\\\\/g; s/"/\\"/g')\"}"
}
BID=$(rd CFBundleIdentifier); [ "$BID" = "{{BUNDLE_ID}}" ] && chk bundle_id ok "$BID" || chk bundle_id fail "$BID ≠ {{BUNDLE_ID}}"
V=$(rd CFBundleShortVersionString); B=$(rd CFBundleVersion)
[ "$V" = "$PUB_NAME" ] && [ "$B" = "$PUB_BUILD" ] && chk version ok "$V ($B)" || chk version fail "IPA $V ($B) ≠ pubspec $PUB"
DT=$(rd DTSDKName); [[ "$DT" =~ ^iphoneos([0-9]+) ]] && [ "${BASH_REMATCH[1]}" -ge 26 ] && chk sdk ok "$DT" || chk sdk fail "built with ${DT:-unknown SDK} (need iphoneos26+)"
AUTHY=$(codesign -dvv "$APP" 2>&1 | sed -n 's/^Authority=//p' | head -1)
[[ "$AUTHY" == "Apple Distribution"* || "$AUTHY" == "iPhone Distribution"* ]] && chk signature ok "$AUTHY" || chk signature fail "signed by '${AUTHY:-nothing}' — need an Apple Distribution certificate"
[ -f "$APP/embedded.mobileprovision" ] && chk profile ok "embedded.mobileprovision present" || chk profile fail "no embedded.mobileprovision"
if [ -f "$ROOT/ios/Runner/PrivacyInfo.xcprivacy" ]; then
  [ -f "$APP/PrivacyInfo.xcprivacy" ] && chk privacy ok "PrivacyInfo.xcprivacy bundled" || chk privacy fail "PrivacyInfo.xcprivacy not in the .app — add it to the Runner target"
fi
SHA=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || true); DIRTY=$([ -n "$(git -C "$ROOT" status --porcelain 2>/dev/null)" ] && echo true || echo false)
printf '{"ipa":"%s","at":"%s","git_sha":"%s","dirty":%s,"xcode":"%s","sdk":"%s","team":"%s","passed":%s,"checks":[%s]}\n' \
  "${IPA#$ROOT/}" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SHA" "$DIRTY" "$XV" "$SDK" "$TEAM" \
  "$([ $FAIL -eq 0 ] && echo true || echo false)" "$ROWS" > "$KIT/build-verify.json"
echo "report: ios-release/build-verify.json"
[ $FAIL -eq 0 ] || die "IPA built but verification failed — do not upload it" 1

cat <<EOF

IPA ready: ${IPA#$ROOT/}  ($(du -h "$IPA" | cut -f1))
Not uploaded. To upload when you decide to:
  • Transporter app (Mac App Store) → drag the .ipa → Deliver, or
  • xcrun altool --upload-app -t ios -f "${IPA#$ROOT/}" --apiKey \$ASC_KEY_ID --apiIssuer \$ASC_ISSUER_ID
Then in App Store Connect: TestFlight → export compliance (already answered if ITSAppUsesNonExemptEncryption is set).
EOF
