#!/usr/bin/env bash
# Emit gradle/libs.versions.toml with the newest STABLE versions, read from the
# repositories Gradle itself resolves against. Falls back to pinned values offline.
#
#   bash resolve-versions.sh > gradle/libs.versions.toml
#
# Why this exists: a hardcoded version pin fails months later at dependency
# resolution, minutes into a build, with an error that reads like a network fault.
set -uo pipefail

GOOGLE=https://dl.google.com/dl/android/maven2
CENTRAL=https://repo1.maven.org/maven2

# latest <repo> <group/path> <version-regex> <fallback>
latest() {
  local out
  out=$(curl -sfL --max-time 12 "$1/$2/maven-metadata.xml" 2>/dev/null \
        | grep -oE '<version>[^<]+</version>' \
        | sed 's/<[^>]*>//g' \
        | grep -vEi 'alpha|beta|rc|dev|eap|-M[0-9]|snapshot' \
        | grep -E "$3" \
        | sort -V | tail -1)
  if [ -n "$out" ]; then echo "$out"; else echo "$4"; STALE=1; fi
}

STALE=0

# AGP: newest stable 8.x on purpose. AGP 9 dropped kotlinOptions and several
# variant APIs, so most Gradle snippets in circulation break against it.
AGP=$(latest      "$GOOGLE"  com/android/tools/build/gradle        '^8\.'   "8.13.2")
KOTLIN=$(latest   "$CENTRAL" org/jetbrains/kotlin/kotlin-gradle-plugin '^2\.' "2.4.10")
BOM=$(latest      "$GOOGLE"  androidx/compose/compose-bom          '^20'    "2026.06.01")
CORE=$(latest     "$GOOGLE"  androidx/core/core-ktx                '^1\.'   "1.19.0")
ACTIVITY=$(latest "$GOOGLE"  androidx/activity/activity-compose    '^1\.'   "1.13.0")

cat <<TOML
# Generated by android-game-forge/scripts/resolve-versions.sh
[versions]
agp = "$AGP"
kotlin = "$KOTLIN"
composeBom = "$BOM"
coreKtx = "$CORE"
activityCompose = "$ACTIVITY"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# The Compose compiler plugin version must always equal the Kotlin version.
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
TOML

if [ "$STALE" -eq 1 ]; then
  echo "WARN: at least one version came from the offline fallback and may be stale." >&2
  echo "      Re-run with network access if dependency resolution fails." >&2
fi
